// A2A JSON-RPC endpoint for UnlockSaaS Agent
// Auto-generated by build-a2a-all-sites.py
import { NextRequest, NextResponse } from "next/server";

const AGENT_CARD = {
  "protocolVersion": "0.3.0",
  "name": "UnlockSaaS Agent",
  "description": "SaaS launch toolkit and community. Alternatives directory, launch checklist, SaaS mistakes guide, revenue projector, LTV calculator, churn cost calculator, and SaaS playbook.",
  "url": "https://unlocksaas.com/api/a2a",
  "preferredTransport": "JSONRPC",
  "version": "1.0.0",
  "capabilities": {"streaming": false, "pushNotifications": false, "stateTransitionHistory": false},
  "defaultInputModes": ["text/plain", "application/json"],
  "defaultOutputModes": ["text/plain", "application/json"],
  "skills": [
    {"id": "get_churn_cost", "name": "Calculate Churn Cost", "description": "Calculate the cost of SaaS churn based on MRR, churn rate, and CAC.", "tags": ["saas", "churn", "metrics", "calculator"], "examples": ["What's my churn cost?", "How much is churn costing me?"]},
    {"id": "get_ltv", "name": "Calculate LTV", "description": "Calculate customer lifetime value (LTV) from ARPU, gross margin, and churn rate.", "tags": ["saas", "ltv", "metrics", "calculator"], "examples": ["Calculate my LTV", "What's my customer lifetime value?"]},
    {"id": "project_revenue", "name": "Project Revenue", "description": "Project SaaS revenue 12 months forward from current MRR and growth assumptions.", "tags": ["saas", "revenue", "projection", "calculator"], "examples": ["Project my revenue", "Forecast MRR growth"]}
  ]
};

const FAQS = [
  {"q": "What is UnlockSaaS?", "a": "UnlockSaaS is a SaaS launch toolkit with alternatives directory, launch checklist, revenue/LTV/churn calculators, and founder playbooks."},
  {"q": "How do I launch a SaaS?", "a": "Follow the UnlockSaaS launch checklist: validate idea, build MVP, set up analytics, launch on Product Hunt, iterate based on feedback."},
  {"q": "What alternatives do you compare?", "a": "We compare popular tools like Notion, Airtable, Lovable, Replit, v0, Cursor, ClickUp, Framer, and ShipFast with detailed feature breakdowns."}
];

export async function GET() {
  return NextResponse.json(AGENT_CARD);
}

export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => ({}));
  const { jsonrpc, method, params, id } = body;

  const headers = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
  };

  if (!jsonrpc || jsonrpc !== "2.0") {
    return NextResponse.json(
      { jsonrpc: "2.0", error: { code: -32600, message: "Invalid Request" }, id: id ?? null },
      { headers }
    );
  }

  switch (method) {
    case "rpc.discover":
    case "agent/card":
      return NextResponse.json(
        { jsonrpc: "2.0", id, result: AGENT_CARD },
        { headers }
      );

    case "faq.search": {
      const query = (params?.query || "").toLowerCase();
      const matches = FAQS.filter(
        (f) => f.q.toLowerCase().includes(query) || f.a.toLowerCase().includes(query)
      );
      return NextResponse.json(
        { jsonrpc: "2.0", id, result: { faqs: matches, total: matches.length } },
        { headers }
      );
    }

    // Legacy method support
    case "agent/info":
    case "agent.describe":
      return NextResponse.json({
        jsonrpc: "2.0",
        result: { name: AGENT_CARD.name, description: AGENT_CARD.description, url: AGENT_CARD.url, capabilities: AGENT_CARD.capabilities, version: AGENT_CARD.version },
        id,
      }, { headers });

    case "agent/capabilities":
    case "agent/query":
    case "agent/search": {
      const query = (params?.query || params?.q || "").toLowerCase();
      const filtered = FAQS.filter(f => f.q.toLowerCase().includes(query) || f.a.toLowerCase().includes(query));
      return NextResponse.json({
        jsonrpc: "2.0",
        result: { query, results: filtered.map(f => ({ title: f.q, description: f.a })), total: filtered.length },
        id,
      }, { headers });
    }

    default:
      return NextResponse.json(
        {
          jsonrpc: "2.0",
          id,
          result: {
            agent: AGENT_CARD.name,
            description: AGENT_CARD.description,
            skills: AGENT_CARD.skills.map((s) => ({ id: s.id, name: s.name, description: s.description })),
            faqs: { total: FAQS.length, searchable: true }
          }
        },
        { headers }
      );
  }
}

export async function OPTIONS() {
  return new NextResponse(null, {
    status: 204,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
    },
  });
}
