/**
 * JSON-LD structured-data blocks for UnlockSaaS — Surface B (AEO/GEO) of the
 * Google strategy. See strategy/google-strategy.md §B.2.
 *
 * Each component renders a single <script type="application/ld+json"> tag.
 * Server-rendered so it's present on first paint for crawlers.
 *
 * Brunson Hard-Rule reconciliation: aggregateRating is intentionally omitted
 * from the Product block until verified customers with public ratings exist.
 * No fabricated review counts. See strategy/google-strategy.md §B.2 + the
 * `honest claims` row of the Brunson Hard-Rule table.
 *
 * Implementation note: every structured-data object is hoisted to module
 * scope and pre-serialized to JSON. The components are pure renders — no
 * per-request allocation, no per-render serialization. This is the
 * `server-hoist-static-io` + `rendering-hoist-jsx` pattern from the
 * Vercel React Best Practices guide.
 */

import { PLAYBOOK_STEPS } from "@/lib/playbook-steps";

const BASE = "https://unlocksaas.com";

/**
 * Speakable Specification cssSelector list.
 *
 * Surface B (AEO + voice-engine optimization) extension. Schema.org's
 * `Speakable` property tells text-to-speech engines (Google Assistant,
 * Siri-style retrieval, screen-readers that follow the spec) which DOM
 * nodes are safe to read aloud — i.e. the prose, not the navigation /
 * call-to-action / footer.
 *
 * Two layout rules for callers:
 *   1. Selectors MUST point at DOM that actually exists on the rendered
 *      page. A Speakable selector pointing at a non-existent node is the
 *      same drift class as a JSON-LD field that disagrees with rendered
 *      text — both get the page demoted in voice answer panels.
 *   2. Prefer stable class names prefixed with `aeo-` (e.g. `.aeo-q`,
 *      `.aeo-a`, `.aeo-tldr`) over heading-tag selectors. Tag selectors
 *      pick up nav links and CTA copy that should not be spoken; an
 *      explicit class lets each page opt the right nodes in.
 *
 * Schema.org reference: https://schema.org/SpeakableSpecification
 */
export type SpeakableSelectors = ReadonlyArray<string>;

function speakableSpec(selectors: SpeakableSelectors) {
  return {
    "@type": "SpeakableSpecification",
    cssSelector: selectors,
  };
}

/**
 * Off-platform entity anchors shared by Organization.sameAs and Person.sameAs.
 *
 * LLMs (Perplexity, ChatGPT, Claude, Gemini) and Google's Knowledge Graph
 * walk `sameAs` to link the UnlockSaaS entity to its representation on other
 * indexed sites. Empty list = isolated entity = ~zero topical authority lift.
 *
 * **Activation rule** (Brunson Hard-Rule: no fabricated identity):
 *   Only append a URL once the linked profile actually exists, is public,
 *   and credibly identifies Maryan / Unlock SaaS. Do not seed placeholders.
 *   strategy/google-strategy.md §B.3 (off-platform signal loop) is the
 *   publishing schedule that fills this list.
 *
 * Suggested order to fill, by GEO/AIO impact per effort:
 *   1. Twitter/X profile        2. Indie Hackers profile
 *   3. LinkedIn personal        4. GitHub
 *   5. YouTube channel          6. Crunchbase company page
 *   7. Wikidata Q-number
 */
const SAME_AS: readonly string[] = [
  // Activation slot. See activation rule above.
];

// --- Pre-built JSON strings (module-level; serialized once at import time) ---

// `logo` resolves to /icon.svg — served by app/icon.svg via Next.js' file-based
// icon convention. iOS home-screen icon at 180×180 PNG is generated by
// app/apple-icon.tsx via next/og ImageResponse. Google accepts SVG for
// Organization.logo (since 2023); a 112×112-min PNG would unlock richer
// Knowledge-Graph rendering when brand-identity work ships.
const ORGANIZATION_JSON = JSON.stringify({
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Unlock SaaS",
  legalName: "Unlock SaaS",
  url: BASE,
  logo: `${BASE}/icon.svg`,
  description:
    "A playbook that turns your already-shipped product into a verified paying customer. If it does not, you do not pay.",
  // Locale anchor. Mirrors the en-US signal shipped in the WebSite block and
  // the layout-level hreflang alternates. LLMs that build entity cards from
  // JSON-LD read `inLanguage` to decide which language audience this
  // organization serves; Google reads it as a corroborating International
  // SEO signal alongside hreflang.
  inLanguage: "en-US",
  founder: {
    "@type": "Person",
    name: "Maryan",
    email: "maryan@unlocksaas.com",
    url: `${BASE}/about`,
  },
  contactPoint: {
    "@type": "ContactPoint",
    contactType: "customer support",
    email: "maryan@unlocksaas.com",
    url: `${BASE}/contact`,
    // BCP 47 locale tag. Matches inLanguage ("en-US"), <html lang>,
    // Content-Language HTTP header, and Service.availableLanguage so the
    // locale signal is internally consistent across every structured-data
    // surface. Prior value was the ISO 639-1 "en" which is valid per
    // schema.org but triggers "Item may be missing or invalid" warnings in
    // some Rich Results testers and weakens the locale signal that LLMs
    // aggregate across the entity. Normalized 2026-05-17.
    availableLanguage: ["en-US"],
  },
  sameAs: SAME_AS,
});

const WEBSITE_JSON = JSON.stringify({
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: "Unlock SaaS",
  url: BASE,
  inLanguage: "en-US",
});

const DIAGNOSTIC_SERVICE_JSON = JSON.stringify({
  "@context": "https://schema.org",
  "@type": "Service",
  name: "Free Launch Diagnostic",
  description:
    "Paste your live product URL. In 90 seconds we label what is actually wrong with one of three diagnoses: Wrong Person, Weak Offer, or Weak Belief — and hand you the door that fixes it.",
  inLanguage: "en-US",
  availableLanguage: ["en-US"],
  provider: {
    "@type": "Organization",
    name: "Unlock SaaS",
    url: BASE,
  },
  serviceType: "Pre-launch SaaS diagnostic",
  audience: {
    "@type": "Audience",
    audienceType:
      "Post-launch pre-revenue non-engineer founders using AI tools",
  },
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
    availability: "https://schema.org/InStock",
  },
  url: `${BASE}/diagnostic`,
});

const DIAGNOSTIC_HOWTO_JSON = JSON.stringify({
  "@context": "https://schema.org",
  "@type": "HowTo",
  name: "How to get a free diagnosis of your stuck SaaS",
  description:
    "A three-step process that labels what is actually broken on your already-shipped product page.",
  inLanguage: "en-US",
  step: [
    {
      "@type": "HowToStep",
      position: 1,
      name: "Paste your URL",
      text: "Paste the live URL of your shipped product and your email address.",
    },
    {
      "@type": "HowToStep",
      position: 2,
      name: "Get the labeled diagnosis",
      text: "Within 90 seconds, get back one of three diagnoses: Wrong Person, Weak Offer, or Weak Belief.",
    },
    {
      "@type": "HowToStep",
      position: 3,
      name: "Walk through the door",
      text: "The diagnosis hands you the specific next step that fixes the labeled problem.",
    },
  ],
  totalTime: "PT90S",
  // Speakable: the "What I am reading on your page" section on /diagnostic
  // renders the three diagnoses (Wrong Person / Weak Offer / Weak Belief) as
  // a bulleted list. Class `.aeo-diagnostic-howto` on that <section> makes
  // the same three answers voice-readable.
  speakable: speakableSpec([".aeo-diagnostic-howto"]),
});

/**
 * The seven-step Playbook as schema.org `HowTo`.
 *
 * Mounted on `/playbook-sales`. The same `PLAYBOOK_STEPS` array feeds the
 * "## The seven steps" section in `/playbook-sales.md` and `/llms-full.txt`
 * via `src/lib/seo/markdown.ts`, so the HowTo schema, the visible HTML
 * page, and the markdown mirror cannot drift.
 *
 * Why HowTo (not Article) for the seven steps: a numbered named-step list
 * is the literal shape Google's featured-snippet engine pulls when a
 * searcher types "how to get my first paying SaaS customer." Article fires
 * a generic Rich Result; HowTo fires the carousel-style step Rich Result
 * AND voice-answer eligibility, which is the entire AEO point.
 *
 * `estimatedCost` and `totalTime` are real, contracted values: $98 capped
 * exposure (the two-month Core price), 60 days from Playbook start. Both
 * are stated on /playbook-sales and in /faq verbatim; the Brunson Hard-Rule
 * "every schema field is in the public HTML" check passes.
 */
const PLAYBOOK_HOWTO_JSON = JSON.stringify({
  "@context": "https://schema.org",
  "@type": "HowTo",
  name: "How to get your first paying SaaS customer in 60 days",
  description:
    "The Unlock SaaS Playbook is a seven-step system that turns an already-shipped SaaS into a verified paying customer in 60 days, or the founder is refunded automatically.",
  inLanguage: "en-US",
  totalTime: "P60D",
  estimatedCost: {
    "@type": "MonetaryAmount",
    currency: "USD",
    value: "98",
  },
  supply: [
    {
      "@type": "HowToSupply",
      name: "A live, already-shipped SaaS product (any stack — Lovable, Claude, Replit, v0, Cursor, Bolt, Bubble, hand-coded).",
    },
    {
      "@type": "HowToSupply",
      name: "A connected Stripe account (the guarantee reads from it).",
    },
    {
      "@type": "HowToSupply",
      name: "Willingness to do at least 20 logged outreach actions over 60 days.",
    },
  ],
  tool: [
    {
      "@type": "HowToTool",
      name: "The Playbook engine — outreach generation, response tracking, Stripe-webhook verification.",
    },
  ],
  step: PLAYBOOK_STEPS.map((s, i) => ({
    "@type": "HowToStep",
    position: i + 1,
    name: s.name,
    text: s.text,
    url: `${BASE}/playbook-sales#step-${i + 1}`,
  })),
  // Speakable: the seven steps render on /playbook-sales inside the Block 2
  // "Three Secrets" prose. Class `.aeo-playbook-howto` on the wrapping
  // <section> opts that block into voice answer panels.
  speakable: speakableSpec([".aeo-playbook-howto"]),
});

// Multi-typed as Product + SoftwareApplication: schema.org allows array @type
// and Google indexes both. The SoftwareApplication facet lets LLMs answer
// "what SaaS tool helps me get my first paying customer" with the entity name,
// while Product keeps the priced offer Rich Result eligible.
const PLAYBOOK_PRODUCT_JSON = JSON.stringify({
  "@context": "https://schema.org",
  "@type": ["Product", "SoftwareApplication"],
  name: "The Playbook — Unlock SaaS",
  description:
    "A seven-step playbook that turns an already-shipped SaaS into a verified paying customer in 60 days, or the founder does not pay. Built by a non-engineer for non-engineer founders shipping with AI tools.",
  brand: {
    "@type": "Brand",
    name: "Unlock SaaS",
  },
  url: `${BASE}/playbook-sales`,
  inLanguage: "en-US",
  applicationCategory: "BusinessApplication",
  operatingSystem: "Web",
  audience: {
    "@type": "Audience",
    audienceType:
      "Post-launch pre-revenue non-engineer founders using AI tools",
  },
  offers: {
    "@type": "Offer",
    price: "49",
    priceCurrency: "USD",
    availability: "https://schema.org/InStock",
    url: `${BASE}/playbook-sales`,
    seller: {
      "@type": "Organization",
      name: "Unlock SaaS",
    },
  },
  // aggregateRating intentionally omitted — see file header.
});

// --- Founder (Person) ------------------------------------------------------
// Anchors the entity graph: LLMs link "Maryan, founder of Unlock SaaS" to the
// Organization above via the shared founder reference. ProfilePage on `/` is
// the canonical place to render this; the empty sameAs[] is the same
// honest-state pattern as Organization — fills as the founder publishes.
const PERSON_JSON = JSON.stringify({
  "@context": "https://schema.org",
  "@type": "Person",
  name: "Maryan",
  url: `${BASE}/about`,
  mainEntityOfPage: {
    "@type": "ProfilePage",
    "@id": `${BASE}/about`,
  },
  email: "maryan@unlocksaas.com",
  jobTitle: "Founder",
  // Author-language signal for E-E-A-T attribution on /stories and any
  // future bylined content. Mirrors Organization.inLanguage.
  knowsLanguage: ["en-US"],
  description:
    "Marketer and non-engineer. Built a dozen AI products with Lovable and Claude, watched them flatline in Stripe, then built the Playbook to fix the work nobody taught indie SaaS founders to do.",
  knowsAbout: [
    "Customer development",
    "Sales funnel design",
    "Indie SaaS go-to-market",
    "Russell Brunson DotCom Secrets framework",
    "AI-assisted product development",
  ],
  worksFor: {
    "@type": "Organization",
    name: "Unlock SaaS",
    url: BASE,
  },
  sameAs: SAME_AS,
});

// --- Dynamic-input schema builders ------------------------------------------
// These accept caller-supplied data and serialize per render. Per-render cost
// is bounded (short arrays, no I/O) and the alternative — module-level
// memoization keyed by reference identity — adds complexity that doesn't pay
// for itself on a page that renders once per request via SSR. Strings are
// JSON-stringified by the helpers, so embedded quotes and HTML-like chars are
// safely escaped before reaching dangerouslySetInnerHTML.

export type FaqItem = { q: string; a: string };

function buildFaqPageJson(
  items: ReadonlyArray<FaqItem>,
  speakable?: SpeakableSelectors,
): string {
  return JSON.stringify({
    "@context": "https://schema.org",
    "@type": "FAQPage",
    inLanguage: "en-US",
    mainEntity: items.map((it) => ({
      "@type": "Question",
      name: it.q,
      acceptedAnswer: {
        "@type": "Answer",
        text: it.a,
      },
    })),
    // Speakable is optional because the FAQ accordion variant on
    // /playbook-sales hides answers in collapsed `<details>` — pointing
    // voice engines at hidden text is the same drift class as a JSON-LD
    // field that disagrees with rendered text. The /faq surface, where
    // every answer is always visible, opts in by passing selectors.
    ...(speakable ? { speakable: speakableSpec(speakable) } : {}),
  });
}

export type ArticleSchemaInput = {
  headline: string;
  description: string;
  url: string;
  datePublished: string; // ISO 8601
  dateModified?: string; // ISO 8601 — defaults to datePublished
  imageUrl?: string;
  /**
   * Speakable cssSelector list. Pass for long-form editorial pages where a
   * voice assistant should read the TL;DR / lede / per-story heading prose
   * but NOT the nav links or opt-in CTA. See SpeakableSelectors docs.
   */
  speakableSelectors?: SpeakableSelectors;
};

function buildArticleJson(input: ArticleSchemaInput): string {
  return JSON.stringify({
    "@context": "https://schema.org",
    "@type": "Article",
    headline: input.headline,
    description: input.description,
    url: input.url,
    inLanguage: "en-US",
    datePublished: input.datePublished,
    dateModified: input.dateModified ?? input.datePublished,
    author: {
      "@type": "Person",
      name: "Maryan",
      url: BASE,
    },
    publisher: {
      "@type": "Organization",
      name: "Unlock SaaS",
      url: BASE,
    },
    mainEntityOfPage: {
      "@type": "WebPage",
      "@id": input.url,
    },
    ...(input.imageUrl ? { image: input.imageUrl } : {}),
    ...(input.speakableSelectors
      ? { speakable: speakableSpec(input.speakableSelectors) }
      : {}),
  });
}

export type BreadcrumbTrail = ReadonlyArray<{ name: string; url: string }>;

function buildBreadcrumbJson(trail: BreadcrumbTrail): string {
  return JSON.stringify({
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: trail.map((crumb, idx) => ({
      "@type": "ListItem",
      position: idx + 1,
      name: crumb.name,
      item: crumb.url,
    })),
  });
}

/**
 * VideoObject — render on any page hosting the founder VSL.
 *
 * `contentUrl` and `embedUrl` are deliberately optional: until the VSL has a
 * stable hosted URL (Mux, YouTube, or a Vercel-served MP4), we still want to
 * publish `name`, `description`, `uploadDate`, and `thumbnailUrl` so LLMs and
 * Google can attach the entity to the page even with the playable asset
 * pointing at the page itself. Schema.org permits `contentUrl` to be the
 * canonical page URL while the asset is in flight, but it lowers Rich-Results
 * eligibility — flag the upgrade in strategy/google-strategy.md when the VSL
 * lands on a CDN.
 */
export type VideoSchemaInput = {
  name: string;
  description: string;
  uploadDate: string; // ISO 8601 (YYYY-MM-DD or full ISO datetime)
  thumbnailUrl: string;
  durationISO8601?: string; // e.g. "PT4M30S"
  contentUrl?: string;
  embedUrl?: string;
  transcriptUrl?: string;
};

function buildVideoJson(input: VideoSchemaInput): string {
  return JSON.stringify({
    "@context": "https://schema.org",
    "@type": "VideoObject",
    name: input.name,
    description: input.description,
    uploadDate: input.uploadDate,
    thumbnailUrl: [input.thumbnailUrl],
    publisher: {
      "@type": "Organization",
      name: "Unlock SaaS",
      url: BASE,
    },
    ...(input.durationISO8601 ? { duration: input.durationISO8601 } : {}),
    ...(input.contentUrl ? { contentUrl: input.contentUrl } : {}),
    ...(input.embedUrl ? { embedUrl: input.embedUrl } : {}),
    ...(input.transcriptUrl ? { transcript: input.transcriptUrl } : {}),
  });
}

// --- Render helpers ----------------------------------------------------------

function JsonLdScript({ json }: { json: string }) {
  return (
    <script
      type="application/ld+json"
      // json is pre-serialized at module load from static, hard-coded values.
      // No user input flows through this string.
      dangerouslySetInnerHTML={{ __html: json }}
    />
  );
}

/**
 * Organization + WebSite schema. Render on the funnel hub `/`.
 * LLMs anchor on Organization as the entity for UnlockSaaS-related queries.
 */
export function OrganizationJsonLd() {
  return (
    <>
      <JsonLdScript json={ORGANIZATION_JSON} />
      <JsonLdScript json={WEBSITE_JSON} />
    </>
  );
}

/**
 * Service + HowTo schema. Render on `/diagnostic`.
 * The HowTo block is the format LLMs paraphrase when summarizing a process.
 */
export function DiagnosticJsonLd() {
  return (
    <>
      <JsonLdScript json={DIAGNOSTIC_SERVICE_JSON} />
      <JsonLdScript json={DIAGNOSTIC_HOWTO_JSON} />
    </>
  );
}

/**
 * Product schema. Render on `/playbook-sales`.
 *
 * aggregateRating is intentionally omitted until verified customers with
 * public ratings exist. Brunson Hard-Rule (honest claims): no fabricated
 * review counts in structured data, ever.
 */
export function PlaybookProductJsonLd() {
  return <JsonLdScript json={PLAYBOOK_PRODUCT_JSON} />;
}

/**
 * Person schema for Maryan. Render on the funnel hub `/` and on `/about`
 * once that page exists. Anchors author/E-E-A-T claims to a single entity.
 */
export function PersonJsonLd() {
  return <JsonLdScript json={PERSON_JSON} />;
}

/**
 * FAQPage schema. Caller passes the same FAQ array it renders as visible
 * HTML — Google penalizes Rich Results when schema diverges from rendered
 * text, so the source of truth lives in src/lib/content/faqs.ts and both
 * the page and this component import from there.
 *
 * Optional `speakableSelectors`: pass a cssSelector list for surfaces where
 * every answer is always-visible (e.g. /faq) so voice engines opt in. The
 * accordion variant on /playbook-sales should NOT pass this — hidden text
 * is invisible to voice and creates schema↔DOM drift.
 */
export function FaqPageJsonLd({
  items,
  speakableSelectors,
}: {
  items: ReadonlyArray<FaqItem>;
  speakableSelectors?: SpeakableSelectors;
}) {
  return <JsonLdScript json={buildFaqPageJson(items, speakableSelectors)} />;
}

/**
 * HowTo schema for the seven-step Playbook. Render on `/playbook-sales`.
 *
 * Mounted alongside `PlaybookProductJsonLd` (the priced Offer) so a single
 * page emits two complementary Rich-Result candidacies: HowTo (the seven
 * steps, voice-answer eligible via the Speakable child) AND Product (the
 * priced offer that powers AI Overviews price-pull). Both fields are drawn
 * from `PLAYBOOK_STEPS` and the canonical `BASE` constant — no per-render
 * allocation, no drift surface.
 */
export function PlaybookHowToJsonLd() {
  return <JsonLdScript json={PLAYBOOK_HOWTO_JSON} />;
}

/**
 * Article schema. Render on long-form content pages (e.g. `/stories`) so
 * LLMs and Google attach author + publish date + canonical URL to the
 * narrative content. Caller supplies the publishing dates from the page
 * to avoid baking build-time dates into the serialized claim.
 */
export function ArticleJsonLd(props: ArticleSchemaInput) {
  return <JsonLdScript json={buildArticleJson(props)} />;
}

/**
 * BreadcrumbList schema. Render on every non-hub page. Crumb trail must
 * mirror the visible site navigation; for UnlockSaaS most surfaces are
 * two-deep (`Home › <Surface>`). Exported as `BreadcrumbListJsonLd` so the
 * component name matches the schema.org `BreadcrumbList` type — easier for
 * future authors to grep and matches the convention used by /about's import.
 */
export function BreadcrumbListJsonLd({ trail }: { trail: BreadcrumbTrail }) {
  return <JsonLdScript json={buildBreadcrumbJson(trail)} />;
}

/**
 * VideoObject schema. Render alongside the VSL block. See VideoSchemaInput
 * docs above: omitting `contentUrl`/`embedUrl` is supported but lowers
 * Rich-Results eligibility — wire them once the VSL ships on a CDN.
 */
export function VideoJsonLd(props: VideoSchemaInput) {
  return <JsonLdScript json={buildVideoJson(props)} />;
}

// Duplicate `export function` declarations of PersonJsonLd, ArticleJsonLd,
// FaqPageJsonLd, and BreadcrumbListJsonLd previously sat below this point —
// concurrent build sessions landed two copies plus a stale re-export alias.
// Canonical exports are above this line. The alias below preserves the older
// `BreadcrumbJsonLd` import name used by /faq/page.tsx (and any other caller
// that has not migrated to the schema.org-literal `BreadcrumbListJsonLd` name)
// so renames in this file do not break consumers.
export { BreadcrumbListJsonLd as BreadcrumbJsonLd };
