/**
 * JSON-LD structured-data blocks for UnlockSaaS — Surface B (AEO/GEO) of the
 * Google strategy. See strategy/google-strategy.md §B.2.
 *
 * Each component renders a single <script type="application/ld+json"> tag.
 * Server-rendered so it's present on first paint for crawlers.
 *
 * Brunson Hard-Rule reconciliation: aggregateRating is intentionally omitted
 * from the Product block until verified customers with public ratings exist.
 * No fabricated review counts. See strategy/google-strategy.md §B.2 + the
 * `honest claims` row of the Brunson Hard-Rule table.
 *
 * Implementation note: every structured-data object is hoisted to module
 * scope and pre-serialized to JSON. The components are pure renders — no
 * per-request allocation, no per-render serialization. This is the
 * `server-hoist-static-io` + `rendering-hoist-jsx` pattern from the
 * Vercel React Best Practices guide.
 */

import {
  BASE_URL,
  ID,
  ORGANIZATION,
  ORGANIZATION_SAME_AS,
  KNOWS_ABOUT,
  PRIMARY_AUDIENCE_TYPE,
} from "@/lib/seo/entity";

// Local alias so the schema literals below keep reading like the original
// inline-constant form. BASE_URL is the canonical export from entity.ts.
const BASE = BASE_URL;

/**
 * Off-platform entity anchors shared by Organization.sameAs and Person.sameAs.
 *
 * Sourced from lib/seo/entity.ts which reads NEXT_PUBLIC_UNLOCKSAAS_*_URL env
 * vars at module load. Empty in a fresh checkout (no fabricated identity);
 * the array lights up the moment an operator drops a verified profile URL
 * into Vercel env. See entity.ts header for the activation rule and the
 * complete list of recognized env keys.
 */
const SAME_AS = ORGANIZATION_SAME_AS;

// --- Pre-built JSON strings (module-level; serialized once at import time) ---

// `logo` resolves to /icon.svg — served by app/icon.svg via Next.js' file-based
// icon convention. iOS home-screen icon at 180×180 PNG is generated by
// app/apple-icon.tsx via next/og ImageResponse. Google accepts SVG for
// Organization.logo (since 2023); a 112×112-min PNG would unlock richer
// Knowledge-Graph rendering when brand-identity work ships.
const ORGANIZATION_JSON = JSON.stringify({
  "@context": "https://schema.org",
  "@type": "Organization",
  // @id anchor: lets the Person, WebSite, Product, and Service blocks
  // reference this Organization by @id rather than inlining a duplicate
  // Organization object. Canonical Schema.org pattern for connected
  // entity graphs; Google Knowledge Graph and AI Overview pipelines
  // resolve them as a single node.
  "@id": ID.organization,
  name: ORGANIZATION.name,
  legalName: ORGANIZATION.legalName,
  url: ORGANIZATION.url,
  logo: ORGANIZATION.logo,
  description: ORGANIZATION.description,
  // Audit v2 (Entity / Topical Authority) — fields added:
  //   slogan       Brunson promise; LLMs quote slogans verbatim in answers.
  //   foundingDate strategy-lock date; lets retrieval engines reason recency.
  //   areaServed   Worldwide; honest signal for digital-only product reach.
  //   knowsAbout   Topical-authority anchors (12 entries in entity.ts).
  slogan: ORGANIZATION.slogan,
  foundingDate: ORGANIZATION.foundingDate,
  areaServed: ORGANIZATION.areaServed,
  email: ORGANIZATION.email,
  // Locale anchor. Mirrors the en-US signal shipped in the WebSite block and
  // the layout-level hreflang alternates. LLMs that build entity cards from
  // JSON-LD read `inLanguage` to decide which language audience this
  // organization serves; Google reads it as a corroborating International
  // SEO signal alongside hreflang.
  inLanguage: "en-US",
  knowsAbout: KNOWS_ABOUT,
  // founder is linked by @id, not inlined. This is the canonical entity-
  // graph pattern: the Person block stands alone and is referenced from
  // wherever needed. Cuts duplicated facts and lets crawlers de-dupe.
  founder: { "@id": ID.person },
  contactPoint: {
    "@type": "ContactPoint",
    contactType: "customer support",
    email: ORGANIZATION.email,
    url: `${BASE}/contact`,
    availableLanguage: ["en"],
  },
  sameAs: SAME_AS,
});

const WEBSITE_JSON = JSON.stringify({
  "@context": "https://schema.org",
  "@type": "WebSite",
  "@id": ID.website,
  name: ORGANIZATION.name,
  url: BASE,
  inLanguage: "en-US",
  // publisher cross-link makes WebSite a child of Organization in the
  // entity graph rather than a disconnected sibling. Article and HowTo
  // nodes elsewhere inherit publisher attribution through this edge.
  publisher: { "@id": ID.organization },
});

const DIAGNOSTIC_SERVICE_JSON = JSON.stringify({
  "@context": "https://schema.org",
  "@type": "Service",
  "@id": ID.diagnosticService,
  name: "Free Launch Diagnostic",
  description:
    "Paste your live product URL. In 90 seconds we label what is actually wrong with one of three diagnoses: Wrong Person, Weak Offer, or Weak Belief — and hand you the door that fixes it.",
  inLanguage: "en-US",
  availableLanguage: ["en-US"],
  // provider linked by @id — the canonical Organization above carries the
  // operational facts (founder, contact, sameAs); duplicating them here
  // would risk drift.
  provider: { "@id": ID.organization },
  serviceType: "Pre-launch SaaS diagnostic",
  audience: {
    "@type": "Audience",
    audienceType: PRIMARY_AUDIENCE_TYPE,
  },
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
    availability: "https://schema.org/InStock",
  },
  url: `${BASE}/diagnostic`,
});

const DIAGNOSTIC_HOWTO_JSON = JSON.stringify({
  "@context": "https://schema.org",
  "@type": "HowTo",
  "@id": ID.diagnosticHowTo,
  name: "How to get a free diagnosis of your stuck SaaS",
  description:
    "A three-step process that labels what is actually broken on your already-shipped product page.",
  inLanguage: "en-US",
  step: [
    {
      "@type": "HowToStep",
      position: 1,
      name: "Paste your URL",
      text: "Paste the live URL of your shipped product and your email address.",
    },
    {
      "@type": "HowToStep",
      position: 2,
      name: "Get the labeled diagnosis",
      text: "Within 90 seconds, get back one of three diagnoses: Wrong Person, Weak Offer, or Weak Belief.",
    },
    {
      "@type": "HowToStep",
      position: 3,
      name: "Walk through the door",
      text: "The diagnosis hands you the specific next step that fixes the labeled problem.",
    },
  ],
  totalTime: "PT90S",
});

// Multi-typed as Product + SoftwareApplication: schema.org allows array @type
// and Google indexes both. The SoftwareApplication facet lets LLMs answer
// "what SaaS tool helps me get my first paying customer" with the entity name,
// while Product keeps the priced offer Rich Result eligible.
const MACHINE_PRODUCT_JSON = JSON.stringify({
  "@context": "https://schema.org",
  "@type": ["Product", "SoftwareApplication"],
  "@id": ID.product,
  name: "The Machine — Unlock SaaS",
  description:
    "A seven-step machine that turns an already-shipped SaaS into a verified paying customer in 60 days, or the founder does not pay. Built by a non-engineer for non-engineer founders shipping with AI tools.",
  // brand, manufacturer, and seller all link back to the canonical
  // Organization by @id. Three cross-references on the same Product node
  // is the strongest entity signal an AI Overview pipeline gets when
  // deciding "which company makes this product" — every traversal path
  // resolves to the same #organization.
  brand: { "@id": ID.organization },
  manufacturer: { "@id": ID.organization },
  url: `${BASE}/machine-sales`,
  inLanguage: "en-US",
  applicationCategory: "BusinessApplication",
  operatingSystem: "Web",
  audience: {
    "@type": "Audience",
    audienceType: PRIMARY_AUDIENCE_TYPE,
  },
  offers: {
    "@type": "Offer",
    price: "49",
    priceCurrency: "USD",
    availability: "https://schema.org/InStock",
    url: `${BASE}/machine-sales`,
    seller: { "@id": ID.organization },
  },
  // aggregateRating intentionally omitted — see file header.
});

// --- Founder (Person) ------------------------------------------------------
// Anchors the entity graph: LLMs link "Maryan, founder of Unlock SaaS" to the
// Organization above via the shared founder reference. ProfilePage on `/` is
// the canonical place to render this; the empty sameAs[] is the same
// honest-state pattern as Organization — fills as the founder publishes.
const PERSON_JSON = JSON.stringify({
  "@context": "https://schema.org",
  "@type": "Person",
  name: "Maryan",
  url: `${BASE}/about`,
  mainEntityOfPage: {
    "@type": "ProfilePage",
    "@id": `${BASE}/about`,
  },
  email: "maryan@unlocksaas.com",
  jobTitle: "Founder",
  // Author-language signal for E-E-A-T attribution on /parables and any
  // future bylined content. Mirrors Organization.inLanguage.
  knowsLanguage: ["en-US"],
  description:
    "Marketer and non-engineer. Built a dozen AI products with Lovable and Claude, watched them flatline in Stripe, then built the Machine to fix the work nobody taught indie SaaS founders to do.",
  knowsAbout: [
    "Customer development",
    "Sales funnel design",
    "Indie SaaS go-to-market",
    "Russell Brunson DotCom Secrets framework",
    "AI-assisted product development",
  ],
  worksFor: {
    "@type": "Organization",
    name: "Unlock SaaS",
    url: BASE,
  },
  sameAs: SAME_AS,
});

// --- Dynamic-input schema builders ------------------------------------------
// These accept caller-supplied data and serialize per render. Per-render cost
// is bounded (short arrays, no I/O) and the alternative — module-level
// memoization keyed by reference identity — adds complexity that doesn't pay
// for itself on a page that renders once per request via SSR. Strings are
// JSON-stringified by the helpers, so embedded quotes and HTML-like chars are
// safely escaped before reaching dangerouslySetInnerHTML.

export type FaqItem = { q: string; a: string };

function buildFaqPageJson(items: ReadonlyArray<FaqItem>): string {
  return JSON.stringify({
    "@context": "https://schema.org",
    "@type": "FAQPage",
    inLanguage: "en-US",
    mainEntity: items.map((it) => ({
      "@type": "Question",
      name: it.q,
      acceptedAnswer: {
        "@type": "Answer",
        text: it.a,
      },
    })),
  });
}

export type ArticleSchemaInput = {
  headline: string;
  description: string;
  url: string;
  datePublished: string; // ISO 8601
  dateModified?: string; // ISO 8601 — defaults to datePublished
  imageUrl?: string;
};

function buildArticleJson(input: ArticleSchemaInput): string {
  return JSON.stringify({
    "@context": "https://schema.org",
    "@type": "Article",
    headline: input.headline,
    description: input.description,
    url: input.url,
    inLanguage: "en-US",
    datePublished: input.datePublished,
    dateModified: input.dateModified ?? input.datePublished,
    author: {
      "@type": "Person",
      name: "Maryan",
      url: BASE,
    },
    publisher: {
      "@type": "Organization",
      name: "Unlock SaaS",
      url: BASE,
    },
    mainEntityOfPage: {
      "@type": "WebPage",
      "@id": input.url,
    },
    ...(input.imageUrl ? { image: input.imageUrl } : {}),
  });
}

export type BreadcrumbTrail = ReadonlyArray<{ name: string; url: string }>;

function buildBreadcrumbJson(trail: BreadcrumbTrail): string {
  return JSON.stringify({
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: trail.map((crumb, idx) => ({
      "@type": "ListItem",
      position: idx + 1,
      name: crumb.name,
      item: crumb.url,
    })),
  });
}

/**
 * VideoObject — render on any page hosting the founder VSL.
 *
 * `contentUrl` and `embedUrl` are deliberately optional: until the VSL has a
 * stable hosted URL (Mux, YouTube, or a Vercel-served MP4), we still want to
 * publish `name`, `description`, `uploadDate`, and `thumbnailUrl` so LLMs and
 * Google can attach the entity to the page even with the playable asset
 * pointing at the page itself. Schema.org permits `contentUrl` to be the
 * canonical page URL while the asset is in flight, but it lowers Rich-Results
 * eligibility — flag the upgrade in strategy/google-strategy.md when the VSL
 * lands on a CDN.
 */
export type VideoSchemaInput = {
  name: string;
  description: string;
  uploadDate: string; // ISO 8601 (YYYY-MM-DD or full ISO datetime)
  thumbnailUrl: string;
  durationISO8601?: string; // e.g. "PT4M30S"
  contentUrl?: string;
  embedUrl?: string;
  transcriptUrl?: string;
};

function buildVideoJson(input: VideoSchemaInput): string {
  return JSON.stringify({
    "@context": "https://schema.org",
    "@type": "VideoObject",
    name: input.name,
    description: input.description,
    uploadDate: input.uploadDate,
    thumbnailUrl: [input.thumbnailUrl],
    publisher: {
      "@type": "Organization",
      name: "Unlock SaaS",
      url: BASE,
    },
    ...(input.durationISO8601 ? { duration: input.durationISO8601 } : {}),
    ...(input.contentUrl ? { contentUrl: input.contentUrl } : {}),
    ...(input.embedUrl ? { embedUrl: input.embedUrl } : {}),
    ...(input.transcriptUrl ? { transcript: input.transcriptUrl } : {}),
  });
}

// --- Render helpers ----------------------------------------------------------

function JsonLdScript({ json }: { json: string }) {
  return (
    <script
      type="application/ld+json"
      // json is pre-serialized at module load from static, hard-coded values.
      // No user input flows through this string.
      dangerouslySetInnerHTML={{ __html: json }}
    />
  );
}

/**
 * Organization + WebSite schema. Render on the funnel hub `/`.
 * LLMs anchor on Organization as the entity for UnlockSaaS-related queries.
 */
export function OrganizationJsonLd() {
  return (
    <>
      <JsonLdScript json={ORGANIZATION_JSON} />
      <JsonLdScript json={WEBSITE_JSON} />
    </>
  );
}

/**
 * Service + HowTo schema. Render on `/diagnostic`.
 * The HowTo block is the format LLMs paraphrase when summarizing a process.
 */
export function DiagnosticJsonLd() {
  return (
    <>
      <JsonLdScript json={DIAGNOSTIC_SERVICE_JSON} />
      <JsonLdScript json={DIAGNOSTIC_HOWTO_JSON} />
    </>
  );
}

/**
 * Product schema. Render on `/machine-sales`.
 *
 * aggregateRating is intentionally omitted until verified customers with
 * public ratings exist. Brunson Hard-Rule (honest claims): no fabricated
 * review counts in structured data, ever.
 */
export function MachineProductJsonLd() {
  return <JsonLdScript json={MACHINE_PRODUCT_JSON} />;
}

/**
 * Person schema for Maryan. Render on the funnel hub `/` and on `/about`
 * once that page exists. Anchors author/E-E-A-T claims to a single entity.
 */
export function PersonJsonLd() {
  return <JsonLdScript json={PERSON_JSON} />;
}

/**
 * FAQPage schema. Caller passes the same FAQ array it renders as visible
 * HTML — Google penalizes Rich Results when schema diverges from rendered
 * text, so the source of truth lives in src/lib/content/faqs.ts and both
 * the page and this component import from there.
 */
export function FaqPageJsonLd({ items }: { items: ReadonlyArray<FaqItem> }) {
  return <JsonLdScript json={buildFaqPageJson(items)} />;
}

/**
 * Article schema. Render on long-form content pages (e.g. `/parables`) so
 * LLMs and Google attach author + publish date + canonical URL to the
 * narrative content. Caller supplies the publishing dates from the page
 * to avoid baking build-time dates into the serialized claim.
 */
export function ArticleJsonLd(props: ArticleSchemaInput) {
  return <JsonLdScript json={buildArticleJson(props)} />;
}

/**
 * BreadcrumbList schema. Render on every non-hub page. Crumb trail must
 * mirror the visible site navigation; for UnlockSaaS most surfaces are
 * two-deep (`Home › <Surface>`). Exported as `BreadcrumbListJsonLd` so the
 * component name matches the schema.org `BreadcrumbList` type — easier for
 * future authors to grep and matches the convention used by /about's import.
 */
export function BreadcrumbListJsonLd({ trail }: { trail: BreadcrumbTrail }) {
  return <JsonLdScript json={buildBreadcrumbJson(trail)} />;
}

/**
 * VideoObject schema. Render alongside the VSL block. See VideoSchemaInput
 * docs above: omitting `contentUrl`/`embedUrl` is supported but lowers
 * Rich-Results eligibility — wire them once the VSL ships on a CDN.
 */
export function VideoJsonLd(props: VideoSchemaInput) {
  return <JsonLdScript json={buildVideoJson(props)} />;
}

// Duplicate `export function` declarations of PersonJsonLd, ArticleJsonLd,
// FaqPageJsonLd, and BreadcrumbListJsonLd previously sat below this point —
// concurrent build sessions landed two copies plus a stale re-export alias.
// Canonical exports are above this line. The alias below preserves the older
// `BreadcrumbJsonLd` import name used by /faq/page.tsx (and any other caller
// that has not migrated to the schema.org-literal `BreadcrumbListJsonLd` name)
// so renames in this file do not break consumers.
export { BreadcrumbListJsonLd as BreadcrumbJsonLd };
